global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'victoriametrics'
    static_configs:
      - targets: [ 'victoriametrics:8428' ]
    metrics_path: '/metrics'

  - job_name: 'vmagent'
    static_configs:
      - targets: [ 'vmagent:8429' ]
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]